from typing import Any, Protocol

from fisheye.bus.async_bus import DeliveryReceipt
from fisheye.schema.events import EventEnvelope


class EventJournal(Protocol):
    async def accept(self, event: EventEnvelope) -> DeliveryReceipt: ...
    async def pending(self, limit: int = 100) -> list[tuple[int, EventEnvelope]]: ...
    async def checkpoint(self, scope: str) -> dict[str, Any] | None: ...
    async def commit_analysis(self, sequence, event, state, alerts=(), findings=(), signals=(), errors=()) -> None: ...


class FindingStore(Protocol):
    async def list_findings(self, scope=None, status=None, limit=100, offset=0) -> list[dict[str, Any]]: ...
    async def update_finding(self, finding_id: str, status: str, actor: str) -> dict[str, Any]: ...
